'use client'

import { useState } from 'react'
import { ArrowLeft, ArrowUpLeft, Check, ChevronDown, Clock3, Cpu, HeartHandshake, Menu, Network, Phone, Play, ShieldCheck, Sparkles, Star, X, Zap } from 'lucide-react'

const products = [
  { name: 'MOBI ONE', title: 'ویلچر هوشمند همراه شما', image: '/images/product-wheelchair.png', category: 'شخصی', copy: 'حرکت روان و مستقل، برای هر روز زندگی.' },
  { name: 'MOBI PRO', title: 'قدرت بیشتر، آزادی بیشتر', image: '/images/hero-mobility.png', category: 'حرفه‌ای', copy: 'تجربه‌ای تازه از کنترل و اطمینان.' },
  { name: 'FLEET', title: 'ناوگان خدمات خودران', image: '/images/fleet-service.png', category: 'سازمانی', copy: 'تجربه‌ای هوشمند برای فضاهای پرتردد.' },
]
const faqs = [['آیا محصولات mitech قابل شخصی‌سازی هستند؟', 'بله. متناسب با نیاز کاربر، محیط و نوع استفاده، راهکار و تنظیمات مناسب پیشنهاد می‌شود.'], ['خدمات پس از فروش چگونه ارائه می‌شود؟', 'تیم پشتیبانی mitech از مشاوره پیش از خرید تا نصب، آموزش و سرویس دوره‌ای در کنار شماست.'], ['محصولات برای چه محیط‌هایی مناسب هستند؟', 'محصولات ما برای خانه، مراکز درمانی، فرودگاه‌ها، مجتمع‌های تجاری و فضاهای سازمانی طراحی شده‌اند.'], ['چطور برای خرید یا همکاری اقدام کنم؟', 'فرم تماس را تکمیل کنید تا کارشناسان ما برای یک گفت‌وگوی کوتاه با شما تماس بگیرند.']]

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [sent, setSent] = useState(false)
  const [filter, setFilter] = useState('همه')
  const [faq, setFaq] = useState(0)
  const filters = ['همه', 'شخصی', 'حرفه‌ای', 'سازمانی']
  const visibleProducts = filter === 'همه' ? products : products.filter((product) => product.category === filter)
  const nav = [['محصولات', '#products'], ['فناوری', '#technology'], ['تجربه کاربران', '#experience'], ['سازمانی', '#enterprise'], ['درباره ما', '#about']]

  return <main dir="rtl" className="min-h-screen overflow-hidden bg-background text-foreground">
    <div className="bg-accent px-5 py-2 text-center text-xs font-bold text-accent-foreground">مشاوره تخصصی رایگان برای انتخاب راهکار مناسب شما <a href="#contact" className="mr-2 underline underline-offset-4">همین حالا تماس بگیرید</a></div>
    <header className="sticky top-0 z-50 border-b border-border/70 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8">
      <a href="#home" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-primary text-primary-foreground"><Network size={21}/></span><b className="text-xl tracking-tight">mitech<span className="text-accent">.</span></b></a>
      <nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex">{nav.map(([label, href]) => <a key={href} href={href} className="transition hover:text-foreground">{label}</a>)}</nav>
      <a href="#contact" className="hidden items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-bold text-primary-foreground md:flex">درخواست مشاوره <ArrowLeft size={16}/></a>
      <button className="rounded-lg p-2 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="منو">{menuOpen ? <X/> : <Menu/>}</button>
    </div>{menuOpen && <nav className="flex flex-col gap-5 border-t border-border bg-background px-6 py-6 text-sm md:hidden">{nav.map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav>}</header>

    <section id="home" className="relative mx-auto flex min-h-[690px] max-w-7xl items-center px-5 py-24 lg:min-h-[760px] lg:px-8"><img src="/images/hero-mobility.png" alt="ویلچر هوشمند mitech" className="absolute inset-0 size-full object-cover"/><div className="absolute inset-0 bg-gradient-to-l from-primary via-primary/65 to-primary/10"/><div className="relative max-w-2xl text-primary-foreground animate-rise"><p className="mb-6 flex items-center gap-3 text-sm font-bold text-accent"><span className="h-px w-10 bg-accent"/> فناوری برای زندگی مستقل</p><h1 className="text-balance text-5xl font-bold leading-[1.2] lg:text-7xl">حرکت، دوباره<br/><span className="text-accent">ممکن است.</span></h1><p className="mt-7 max-w-lg text-pretty text-lg leading-8 text-primary-foreground/80">با mitech، مرزهای حرکت را جابه‌جا کنید. محصولاتی هوشمند، انسانی و قابل اعتماد برای اینکه هیچ مسیری محدودکننده نباشد.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#products" className="flex items-center gap-2 rounded-full bg-accent px-6 py-3.5 font-bold text-accent-foreground">کشف محصولات <ArrowLeft size={17}/></a><a href="#story" className="flex items-center gap-2 rounded-full border border-primary-foreground/35 px-6 py-3.5 font-bold hover:bg-primary-foreground/10"><Play size={15}/> داستان mitech</a></div></div><div className="absolute bottom-8 left-8 hidden text-xs text-primary-foreground/60 lg:block">برای انسان‌ها، نه فقط ماشین‌ها</div></section>

    <section className="border-b border-border bg-background"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-x-reverse divide-border sm:grid-cols-4"><div className="p-7 text-center"><b className="text-3xl text-primary">+۱۰</b><p className="mt-2 text-xs text-muted-foreground">سال تجربه و نوآوری</p></div><div className="p-7 text-center"><b className="text-3xl text-primary">+۲۵۰</b><p className="mt-2 text-xs text-muted-foreground">کاربر و سازمان همراه</p></div><div className="p-7 text-center"><b className="text-3xl text-primary">۲۴/۷</b><p className="mt-2 text-xs text-muted-foreground">پشتیبانی و همراهی</p></div><div className="p-7 text-center"><b className="text-3xl text-primary">۱۰۰٪</b><p className="mt-2 text-xs text-muted-foreground">توسعه با دانش بومی</p></div></div></section>

    <section id="products" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="mb-3 text-sm font-bold text-accent">راهکارهای mitech</p><h2 className="text-4xl font-bold lg:text-5xl">برای هر مسیر،<br/><span className="text-muted-foreground">یک راهکار بهتر.</span></h2></div><div className="flex gap-2 rounded-full bg-secondary p-1">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-full px-4 py-2 text-xs font-bold transition ${filter === item ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'}`}>{item}</button>)}</div></div><div className="mt-12 grid gap-5 md:grid-cols-3">{visibleProducts.map((product, index) => <article key={product.name} className={`group overflow-hidden rounded-2xl ${index === 0 ? 'bg-primary text-primary-foreground' : 'bg-secondary'}`}><div className="aspect-[1.15] overflow-hidden"><img src={product.image} alt={product.title} className="size-full object-cover transition duration-700 group-hover:scale-105"/></div><div className="p-6"><p className="mb-2 text-xs font-bold tracking-[.2em] text-accent">{product.name}</p><h3 className="text-xl font-bold">{product.title}</h3><p className="mt-3 text-sm leading-6 opacity-70">{product.copy}</p><div className="mt-6 flex items-center justify-between"><span className="text-xs opacity-60">{product.category}</span><span className="grid size-9 place-items-center rounded-full border border-current/20"><ArrowUpLeft size={17}/></span></div></div></article>)}</div></section>

    <section id="technology" className="bg-secondary px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-14 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div><p className="mb-3 text-sm font-bold text-accent">فناوری که حس می‌شود</p><h2 className="text-4xl font-bold leading-tight lg:text-5xl">هوشمندی،<br/><span className="text-primary">در خدمت شما.</span></h2><p className="mt-6 leading-8 text-muted-foreground">هر جزئیات با یک هدف طراحی شده: کنترل بیشتر، آسودگی بیشتر و تجربه‌ای طبیعی‌تر در تمام مسیر.</p><a href="#contact" className="mt-8 inline-flex items-center gap-2 font-bold text-primary">با متخصصان ما صحبت کنید <ArrowLeft size={16}/></a></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-background p-7"><Cpu className="text-accent"/><h3 className="mt-8 text-lg font-bold">کنترل هوشمند</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">سیستم حرکتی دقیق که با شما و محیط اطراف سازگار می‌شود.</p></div><div className="rounded-2xl bg-background p-7"><ShieldCheck className="text-accent"/><h3 className="mt-8 text-lg font-bold">ایمنی در اولویت</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">تشخیص موانع و تصمیم‌گیری سریع برای حرکت مطمئن.</p></div><div className="rounded-2xl bg-primary p-7 text-primary-foreground sm:col-span-2"><div className="flex items-start justify-between"><div><Zap className="text-accent"/><h3 className="mt-8 text-lg font-bold">ساده‌تر از همیشه</h3><p className="mt-3 max-w-lg text-sm leading-6 text-primary-foreground/70">تکنولوژی واقعی زمانی ارزشمند است که استفاده از آن آسان باشد. رابط کاربری mitech برای تجربه‌ای بی‌دردسر ساخته شده است.</p></div><span className="text-6xl font-bold text-accent/20">∞</span></div></div></div></div></div></section>

    <section id="experience" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div className="overflow-hidden rounded-3xl bg-secondary"><img src="/images/lifestyle-mobility.png" alt="تجربه‌ای آزاد و مستقل در زندگی روزمره" className="aspect-square size-full object-cover"/></div><div><p className="mb-3 text-sm font-bold text-accent">تجربه‌ای که تغییر می‌دهد</p><h2 className="text-4xl font-bold leading-tight lg:text-5xl">زندگی را<br/>با ریتم خودت زندگی کن.</h2><p className="mt-6 leading-8 text-muted-foreground">ما فقط محصول نمی‌سازیم؛ ما تجربه‌ای می‌سازیم که به شما اجازه می‌دهد روی چیزهای مهم زندگی تمرکز کنید.</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-border p-5"><HeartHandshake className="text-accent"/><b className="mt-4 block">طراحی انسانی</b><span className="mt-2 block text-xs leading-5 text-muted-foreground">هر لمس و حرکت با درک نیاز واقعی شما.</span></div><div className="rounded-xl border border-border p-5"><Sparkles className="text-accent"/><b className="mt-4 block">اعتماد روزانه</b><span className="mt-2 block text-xs leading-5 text-muted-foreground">همراهی مطمئن، در خانه و بیرون از خانه.</span></div></div></div></div></section>

    <section id="enterprise" className="bg-primary px-5 py-24 text-primary-foreground lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-8"><div><p className="mb-3 text-sm font-bold text-accent">راهکارهای سازمانی</p><h2 className="text-4xl font-bold leading-tight lg:text-5xl">فضاهای بزرگ‌تر،<br/>تجربه‌ای <span className="text-accent">هوشمندتر.</span></h2></div><p className="max-w-md leading-8 text-primary-foreground/70">از فرودگاه و بیمارستان تا مراکز خرید؛ ناوگان خودران mitech تجربه‌ای روان، ایمن و به‌یادماندنی برای مراجعان می‌سازد.</p></div><div className="mt-12 overflow-hidden rounded-3xl"><img src="/images/fleet-service.png" alt="ناوگان خودران سازمانی mitech" className="h-80 w-full object-cover lg:h-[460px]"/></div><div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="border-t border-primary-foreground/20 pt-5"><b className="text-2xl">کاهش هزینه</b><p className="mt-2 text-sm text-primary-foreground/60">با مدیریت هوشمند ناوگان</p></div><div className="border-t border-primary-foreground/20 pt-5"><b className="text-2xl">داده‌محور</b><p className="mt-2 text-sm text-primary-foreground/60">تصمیم‌گیری دقیق‌تر برای کسب‌وکار</p></div><div className="border-t border-primary-foreground/20 pt-5"><b className="text-2xl">قابل توسعه</b><p className="mt-2 text-sm text-primary-foreground/60">هماهنگ با رشد مجموعه شما</p></div></div></div></section>

    <section id="story" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="rounded-3xl border border-border p-8 lg:p-16"><div className="grid gap-12 lg:grid-cols-2"><div><p className="mb-3 text-sm font-bold text-accent">داستان ما</p><h2 className="text-4xl font-bold leading-tight lg:text-5xl">نوآوری، وقتی<br/><span className="text-muted-foreground">معنادار است.</span></h2></div><div><p className="leading-8 text-muted-foreground">mitech از یک پرسش ساده شروع شد: اگر فناوری بتواند بخشی از محدودیت‌های حرکت را کنار بزند، زندگی چه شکلی خواهد بود؟ امروز، تیمی از مهندسان و طراحان ایرانی هستیم که هر روز برای پاسخ بهتر به این پرسش تلاش می‌کنیم.</p><a href="#about" className="mt-7 inline-flex items-center gap-2 font-bold text-primary">بیشتر درباره mitech <ArrowLeft size={16}/></a></div></div></div></section>

    <section className="bg-secondary px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between"><div><p className="mb-3 text-sm font-bold text-accent">همراهان ما می‌گویند</p><h2 className="text-4xl font-bold">تجربه واقعی،<br/>تغییر واقعی.</h2></div><div className="hidden gap-1 text-accent sm:flex">{[1,2,3,4,5].map((item) => <Star key={item} size={18} fill="currentColor"/>)}</div></div><div className="mt-12 grid gap-5 md:grid-cols-3"><div className="rounded-2xl bg-background p-7 md:col-span-2"><p className="text-xl font-bold leading-9">«mitech فقط یک وسیله حرکتی نیست؛ بخشی از استقلال و اعتمادبه‌نفس من است. حالا برای رفتن به جاهایی که دوست دارم، کمتر فکر می‌کنم.»</p><div className="mt-8 flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-accent font-bold text-accent-foreground">م</div><div><b className="text-sm">مریم رضایی</b><p className="text-xs text-muted-foreground">کاربر MOBI ONE</p></div></div></div><div className="rounded-2xl bg-primary p-7 text-primary-foreground"><Network className="text-accent"/><p className="mt-12 text-lg font-bold leading-8">«یک همکاری حرفه‌ای، دقیق و انسانی از اولین جلسه تا امروز.»</p><p className="mt-6 text-xs text-primary-foreground/60">مدیر توسعه یک مرکز درمانی</p></div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="mb-3 text-sm font-bold text-accent">مجله mitech</p><h2 className="text-4xl font-bold">ایده‌هایی برای<br/><span className="text-muted-foreground">حرکت رو به جلو.</span></h2></div><a href="#contact" className="flex items-center gap-2 font-bold text-primary">مشاهده همه مطالب <ArrowLeft size={16}/></a></div><div className="mt-12 grid gap-5 md:grid-cols-3"><article className="group"><div className="overflow-hidden rounded-2xl bg-secondary"><img src="/images/hero-mobility.png" alt="آینده حمل‌ونقل هوشمند" className="aspect-[1.4] w-full object-cover grayscale transition duration-500 group-hover:scale-105 group-hover:grayscale-0"/></div><p className="mt-5 text-xs font-bold text-accent">فناوری و آینده</p><h3 className="mt-2 text-xl font-bold leading-8">چرا آینده حمل‌ونقل، انسانی‌تر خواهد بود؟</h3></article><article className="group"><div className="overflow-hidden rounded-2xl bg-secondary"><img src="/images/fleet-service.png" alt="فضاهای هوشمند" className="aspect-[1.4] w-full object-cover grayscale transition duration-500 group-hover:scale-105 group-hover:grayscale-0"/></div><p className="mt-5 text-xs font-bold text-accent">راهکار سازمانی</p><h3 className="mt-2 text-xl font-bold leading-8">ساختن فضاهایی که برای همه قابل دسترس‌اند</h3></article><article className="rounded-2xl bg-primary p-7 text-primary-foreground"><Clock3 className="text-accent"/><p className="mt-14 text-xs font-bold text-accent">راهنمای mitech</p><h3 className="mt-3 text-xl font-bold leading-8">۵ نکته برای انتخاب راهکار حرکتی مناسب</h3><a href="#contact" className="mt-7 inline-flex items-center gap-2 text-sm font-bold">مطالعه راهنما <ArrowLeft size={15}/></a></article></div></section>

    <section className="bg-secondary px-5 py-24 lg:px-8"><div className="mx-auto max-w-3xl"><div className="text-center"><p className="mb-3 text-sm font-bold text-accent">پرسش‌های متداول</p><h2 className="text-4xl font-bold">پاسخ پرسش‌های شما</h2></div><div className="mt-10 divide-y divide-border rounded-2xl bg-background px-6">{faqs.map(([question, answer], index) => <div key={question} className="py-5"><button className="flex w-full items-center justify-between text-right font-bold" onClick={() => setFaq(faq === index ? -1 : index)}>{question}<ChevronDown size={18} className={`transition ${faq === index ? 'rotate-180 text-accent' : 'text-muted-foreground'}`}/></button>{faq === index && <p className="mt-4 max-w-2xl text-sm leading-7 text-muted-foreground">{answer}</p>}</div>)}</div></div></section>

    <section id="contact" className="border-t border-border bg-background px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-2"><div><p className="mb-3 text-sm font-bold text-accent">در تماس باشیم</p><h2 className="text-4xl font-bold lg:text-5xl">آماده‌اید<br/>حرکت کنید؟</h2><p className="mt-6 max-w-md leading-8 text-muted-foreground">برای دریافت مشاوره یا اطلاعات بیشتر فرم را تکمیل کنید. کارشناسان mitech با شما تماس می‌گیرند.</p><div className="mt-8 flex items-center gap-3 text-sm"><span className="grid size-10 place-items-center rounded-full bg-secondary text-primary"><Phone size={17}/></span>۰۲۱ - ۸۸۷۷ ۴۴۱۱</div></div><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); setSent(true) }}><input required className="w-full rounded-xl border-0 bg-secondary px-5 py-4 outline-none ring-accent focus:ring-2" placeholder="نام و نام خانوادگی"/><input required type="tel" className="w-full rounded-xl border-0 bg-secondary px-5 py-4 outline-none ring-accent focus:ring-2" placeholder="شماره تماس"/><textarea className="min-h-32 w-full resize-none rounded-xl border-0 bg-secondary px-5 py-4 outline-none ring-accent focus:ring-2" placeholder="چطور می‌توانیم کمک کنیم؟"/><button className="flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-5 py-4 font-bold text-primary-foreground" type="submit">{sent ? <><Check size={18}/> درخواست شما دریافت شد</> : <>ارسال درخواست <ArrowLeft size={17}/></>}</button></form></div></section>

    <footer id="about" className="bg-primary px-5 py-12 text-primary-foreground lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-8 border-b border-primary-foreground/15 pb-10 md:flex-row"><div><div className="flex items-center gap-3 text-xl font-bold"><span className="grid size-10 place-items-center rounded-xl bg-accent text-accent-foreground"><Network size={20}/></span>mitech<span className="text-accent">.</span></div><p className="mt-5 max-w-xs text-sm leading-7 text-primary-foreground/60">فناوری برای زندگی مستقل و آینده‌ای که برای همه حرکت می‌کند.</p></div><div className="grid grid-cols-2 gap-x-14 gap-y-4 text-sm text-primary-foreground/65"><a href="#products">محصولات</a><a href="#technology">فناوری ما</a><a href="#enterprise">راهکار سازمانی</a><a href="#contact">تماس با ما</a></div></div><div className="flex flex-col gap-3 pt-7 text-xs text-primary-foreground/45 md:flex-row md:items-center md:justify-between"><span>© ۱۴۰۳ mitech. تمامی حقوق محفوظ است.</span><span>تهران، ایران · ساخته‌شده برای حرکت</span></div></div></footer>
  </main>
}
